### ISSUE TITLE
Some pointers for starters - docker container or host machine?

### ISSUE THREAD

**Issue by kevinkit** [jimheaton/Vitis-AI-DPU_TRD-for-ZCU106#4]
Hi, 

I am a little bit lost in the wide space of Vitis and Vitis-AI and was hoping for some pointers, sorry if this does not belong here. 

In the Readme it is pointed out that the following steps have to be done:

```
source <path to Vitis Install>/Vitis/2019.2/settings64.sh
source <path to Petalinux Install>Petalinux/2019.2/settings.sh
source /opt/xilinx/xrt/setup.sh
```

On the original [Vitis-Ai](https://github.com/Xilinx/Vitis-AI/blob/master/Vitis-AI-Library/README.md) Vitis-AI gets installed via a container, but the installation of the petalinux is done on the Host machine if one follows the quick guide.

In the container i only find /opt/xilinx but petalinux and Vitis were not findable.

My question is: Do i exeucte those soruce commands in the container (and have to install petalinux  and Vitis there) or do I have to execute those commands on the host machine?

Thank you for your help in advance,

Greetings

**Comment by jimheaton** [comment]
Building the DPU_TRD is a two step process. You don't need to Vitis-AI docker container for either of these.
First create the Vitis Platform using Vivado and Petalinux
Then once the platform is created,  Vitis is used to build the final HW with the DPU kernel. 

After the HW is build by Vitis, you can generate the SD Card image, boot your board, install the Vitis-AI-Libraies and Vart 
The DPU settings are identical to the ZCU104, so you can select the ZCU104 arch file when compiling models with Vitis-AI compiler.

**Comment by kevinkit** [comment]
Thank you for the clarification it is still a little bit cloudy to me:

> First create the Vitis Platform using Vivado and Petalinux

Is Vitis the same as Vitis Platform? In my head Vitis was a standalone tool that I need to install, or can I just use the VIVADO environment?

**Comment by jimheaton** [comment]
A Vitis project needs a platform. The Vitis platform gets created by Vivado, this is the xpfm file that Vitis uses.
