### ISSUE TITLE
will this work for higher versions of VITIS-AI ? 

### ISSUE THREAD

**Issue by kevinkit** [jimheaton/Vitis-AI-DPU_TRD-for-ZCU106#5]
The documentation lists that the supported versions of VITIS-AI are 1.1 - does this mean that it is strictly limited to this version or that one may use 1.2 but is was just not tested yet?

**Comment by jimheaton** [comment]
To be compatible with the Vitis-AI Libaries it would need to be rebuilt with the 2020.1. My design was a migration of the zcu104_dpu Vitis platform. The 2020.1 version of the zcu104_platform would need to be migrated.
